name: alarm_plugin
description: Simple stubbed alarm plugin for local development.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

